version: "3"
services:
  ijulia:
    build: .

    ports:
      - 8888:8888

    volumes:
      - .:/home/jovyan/PlotsGallery
      - $HOME/.Xauthority:/home/jovyan/.Xauthority:rw

    working_dir: /home/jovyan/PlotsGallery
    entrypoint: bash /home/jovyan/PlotsGallery/entrypoint.sh
